wip
Versent/saml2aws pull request #1027
Opened 2023-04-12 17:32 UTC by 6f6d6172

opening this now so I don't forget

2023-04-12 17:36 UTC, 6f6d6172 commented
(only opened it so I could see codecov output, it's still wip)

2023-04-13 00:26 UTC, mapkon requested changes
This needs work:
- Tests are failing
- There are deprecated methods pulled through
- And the coverage will most likely go down

2023-04-13 00:26 UTC, mapkon commented on .goreleaser.ubuntu-latest.yml
> +    - darwin
What is the reasoning for this?

2023-04-13 00:27 UTC, mapkon commented on Makefile
> +BIN_DIR := ./bin
I am not sure I see the difference here, other than hard coding the current directory as the reference for searching the bin directory. What is the purpose of this change?

2023-04-13 22:59 UTC, mapkon commented
@6f6d6172 This is not quite there mate. Please take another look, thanks!

2023-04-14 17:22 UTC, 6f6d6172 commented
@mapkon  Yup! Just working on this between tasks at work :)

2023-04-14 17:23 UTC, 6f6d6172 commented
@mapkon  Yup! Just working on this between tasks at work :) I just got tests running locally.

2023-04-24 15:58 UTC, lizduty commented
confirming this also works for me @6f6d6172 please let me know if you need help!

2023-05-08 15:21 UTC, lizduty commented
@6f6d6172 thank you for your work on this! Couldn't have taken it across the finish line without you and @ctennis

2023-06-18 17:53 UTC, mapkon reviewed
Is this still being considered or should we close the PR?

2023-06-20 22:56 UTC, closed without merging