Use logger instead of fmt.Println in brwoser.go
Versent/saml2aws pull request #1119
Opened 2023-08-31 09:37 UTC by alFReD-NSH

`fmt.Println` still logs when `--quiet` is specified and that's problematic when saml2login is being used as credential_process in aws profiles.

2023-09-01 01:06 UTC, mapkon approved these changes

2023-09-01 02:12 UTC, mapkon requested changes
Please look into the lint errors

2023-09-04 07:25 UTC, alFReD-NSH commented
@mapkon Thanks for the quick review, fixed the lint error.

2023-09-05 02:57 UTC, mapkon approved these changes

2023-09-05 02:58 UTC, merged