Okta + Duo: Allow passcodes from mobile app
Versent/saml2aws pull request #1222
Opened 2024-02-24 21:53 UTC by wlonkly

Any Duo mobile app registered with Duo, usually for Duo Push, also has the capability to produce HOTP passcodes:

<img src="https://github.com/Versent/saml2aws/assets/1545955/9edd5b76-84f0-4db5-9291-9543c929fd74" alt="Duo Mobile app on iOS, showing HOTP code. Yes, I burned that code." width="200"> 

In the case where Duo Push is administratively disabled and Yubikeys (etc) are not provided, HOTP might be the only way for a user to perform Duo MFA. This is the case for us, which is preventing our non-Yubikey users from using saml2aws at all. 

This change adds Passcode to the list of MFA possibilities whenever a `phone1` is registered with Duo, to support using HOTP. 

--- 

I debated between adding it like this, or adding another conditional to the `option[value="token"]` case -- let me know if that would be preferable. I also checked the other Duo-enabled providers, but none of the others use this kind of logic to limit the MFA options presented to the user.

2024-02-26 05:29 UTC, mapkon approved these changes
Looks fine to me. @gliptak / @wolfeidau - any thoughts?

2024-02-26 16:01 UTC, gliptak commented
any related unit test updates?

2024-02-27 00:52 UTC, gliptak commented
@wlonky yes, there seems to be coverage the modified code https://app.codecov.io/gh/Versent/saml2aws/blob/master/pkg%2Fprovider%2Fokta%2Fokta.go#L974

consider creating a copy of https://github.com/Versent/saml2aws/blob/14c45abf5f8dcee4d39a269cf1a55dcf28006643/pkg/provider/okta/okta_test.go#L268 and updating for 1Passcode` path (some processing could be shared between these two flows)

2024-02-28 14:01 UTC, wlonkly commented
Got it, I'll see what I can do! Probably won't get to this until the weekend.

2024-03-01 16:58 UTC, wlonkly commented
Sorted and ready to go!

2024-03-02 22:43 UTC, gliptak commented on pkg/provider/okta/okta_test.go
> +  ts := httptest.NewTLSServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
this seems to have wrong indent

2024-03-02 22:47 UTC, wlonkly commented on pkg/provider/okta/okta_test.go
> +  ts := httptest.NewTLSServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
ty, fixed

2024-03-03 23:57 UTC, mapkon commented
@gliptak Is this ready to merge?

2024-03-04 22:36 UTC, mapkon requested changes
Moving back to needs work since there is an issue with Okta

2024-03-04 22:36 UTC, mapkon commented
> Rats, I need to make one more change -- I just used my local build on my actual work Okta account, and I see duplicate "Passcode" options (because I have both `token` and `phone1` authenticators; my test account only had `phone1`).

OK - just let me know when its ready

2024-03-04 23:42 UTC, wlonkly commented
@mapkon Should be all set now. I switched around the logic to only add `Passcode` once, rather than uniq-ing it at the end.

2024-03-07 22:21 UTC, mapkon approved these changes

2024-03-07 22:21 UTC, merged